apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: davtrowebdb
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: postgres:14
          env:
            - name: POSTGRES_DB
              value: appdb
            - name: POSTGRES_USER
              value: appuser
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: postgres-password
            - name: POSTGRES_HOST_AUTH_METHOD
              value: "md5"
          command:
            - bash
            - -c
            - |
              # Czekaj aż baza będzie gotowa do konfiguracji
              until pg_isready -U appuser -d appdb; do sleep 1; done
              # Dodaj wpis do pg_hba.conf dla połączeń zdalnych
              echo "host all all all md5" >> /var/lib/postgresql/data/pg_hba.conf
              # Uruchom ponownie PostgreSQL aby zastosować zmiany
              pg_ctl restart -D /var/lib/postgresql/data
              # Uruchom serwer
              exec docker-entrypoint.sh postgres
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - exec pg_isready -U appuser -d appdb
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - exec pg_isready -U appuser -d appdb
            initialDelaySeconds: 30
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: davtrowebdb
  labels:
    app: db
spec:
  selector:
    app: db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
