apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: davtrowebdb
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'fastapi'
        metrics_path: /metrics
        static_configs:
          - targets: ['website-db-argocd-kustomize-kyverno-grafana-loki-tempo-pgadmin:8000']
