apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: davtrowebdb
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
    clients:
      - url: http://loki:3100/loki/api/v1/push
    scrape_configs:
      - job_name: fastapi
        static_configs:
          - targets: ['website-db-argocd-kustomize-kyverno-grafana-loki-tempo-pgadmin:8000']
            labels:
              job: fastapi
